/*

* Code generated by Symars. Thank you for using Symars!
  Symars is licensed under MIT licnese.
  Repository: https://github.com/Da1sypetals/Symars

* Computation code is not intended for manual editing.

* If you find an error,
  or if you believe Symars generates incorrect result,
  please raise an issue under our repo with minimal reproducible example.

*/
#![allow(unused)]

use crate::Ad;

#[inline]
pub fn det_4_4_lu<const N: usize>(
    a0: Ad<N>,
    a1: Ad<N>,
    a2: Ad<N>,
    a3: Ad<N>,
    a4: Ad<N>,
    a5: Ad<N>,
    a6: Ad<N>,
    a7: Ad<N>,
    a8: Ad<N>,
    a9: Ad<N>,
    a10: Ad<N>,
    a11: Ad<N>,
    a12: Ad<N>,
    a13: Ad<N>,
    a14: Ad<N>,
    a15: Ad<N>,
) -> Ad<N> {
    let __intermediate_result_3 = (&a0).recip();
    let __intermediate_result_4 = ((&a10)
        + (-((&a2) * (&a8) * ((&a0).recip())))
        + (-((((&a5) + (-((&a1) * (&a4) * ((&a0).recip())))).recip())
            * ((&a6) + (-((&a2) * (&a4) * ((&a0).recip()))))
            * ((&a9) + (-((&a1) * (&a8) * ((&a0).recip())))))));
    let __intermediate_result_7 = ((&a5) + (-((&a1) * (&a4) * ((&a0).recip())))).recip();
    let __intermediate_result_15 = ((&a13) + (-((&a1) * (&a12) * ((&a0).recip()))));
    let __intermediate_result_17 = ((&a7) + (-((&a3) * (&a4) * ((&a0).recip()))));

    ((&a0)
        * ((&a5) + (-((&a1) * (&a4) * (&__intermediate_result_3))))
        * (&__intermediate_result_4)
        * ((&a15)
            + (-((&a12) * (&a3) * (&__intermediate_result_3)))
            + (-((&__intermediate_result_7)
                * (&__intermediate_result_15)
                * (&__intermediate_result_17)))
            + (-(((&__intermediate_result_4).recip())
                * ((&a11)
                    + (-((&a3) * (&a8) * (&__intermediate_result_3)))
                    + (-((&__intermediate_result_7)
                        * (&__intermediate_result_17)
                        * ((&a9) + (-((&a1) * (&a8) * (&__intermediate_result_3)))))))
                * ((&a14)
                    + (-((&a12) * (&a2) * (&__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * (&__intermediate_result_15)
                        * ((&a6) + (-((&a2) * (&a4) * (__intermediate_result_3)))))))))))
}

#[inline]
pub fn det_4_4<const N: usize>(
    a0: Ad<N>,
    a1: Ad<N>,
    a2: Ad<N>,
    a3: Ad<N>,
    a4: Ad<N>,
    a5: Ad<N>,
    a6: Ad<N>,
    a7: Ad<N>,
    a8: Ad<N>,
    a9: Ad<N>,
    a10: Ad<N>,
    a11: Ad<N>,
    a12: Ad<N>,
    a13: Ad<N>,
    a14: Ad<N>,
    a15: Ad<N>,
) -> Ad<N> {
    let a0 = &a0;
    let a1 = &a1;
    let a2 = &a2;
    let a3 = &a3;
    let a4 = &a4;
    let a5 = &a5;
    let a6 = &a6;
    let a7 = &a7;
    let a8 = &a8;
    let a9 = &a9;
    let a10 = &a10;
    let a11 = &a11;
    let a12 = &a12;
    let a13 = &a13;
    let a14 = &a14;
    let a15 = &a15;

    (((a0) * (a10) * (a15) * (a5))
        + ((a0) * (a11) * (a13) * (a6))
        + ((a0) * (a14) * (a7) * (a9))
        + ((a1) * (a10) * (a12) * (a7))
        + ((a1) * (a11) * (a14) * (a4))
        + ((a1) * (a15) * (a6) * (a8))
        + ((a10) * (a13) * (a3) * (a4))
        + ((a11) * (a12) * (a2) * (a5))
        + ((a12) * (a3) * (a6) * (a9))
        + ((a13) * (a2) * (a7) * (a8))
        + ((a14) * (a3) * (a5) * (a8))
        + ((a15) * (a2) * (a4) * (a9))
        + (-((a0) * (a10) * (a13) * (a7)))
        + (-((a0) * (a11) * (a14) * (a5)))
        + (-((a0) * (a15) * (a6) * (a9)))
        + (-((a1) * (a10) * (a15) * (a4)))
        + (-((a1) * (a11) * (a12) * (a6)))
        + (-((a1) * (a14) * (a7) * (a8)))
        + (-((a10) * (a12) * (a3) * (a5)))
        + (-((a11) * (a13) * (a2) * (a4)))
        + (-((a12) * (a2) * (a7) * (a9)))
        + (-((a13) * (a3) * (a6) * (a8)))
        + (-((a14) * (a3) * (a4) * (a9)))
        + (-((a15) * (a2) * (a5) * (a8))))
}

#[inline]
pub fn det_5_5_lu<const N: usize>(
    a0: Ad<N>,
    a1: Ad<N>,
    a2: Ad<N>,
    a3: Ad<N>,
    a4: Ad<N>,
    a5: Ad<N>,
    a6: Ad<N>,
    a7: Ad<N>,
    a8: Ad<N>,
    a9: Ad<N>,
    a10: Ad<N>,
    a11: Ad<N>,
    a12: Ad<N>,
    a13: Ad<N>,
    a14: Ad<N>,
    a15: Ad<N>,
    a16: Ad<N>,
    a17: Ad<N>,
    a18: Ad<N>,
    a19: Ad<N>,
    a20: Ad<N>,
    a21: Ad<N>,
    a22: Ad<N>,
    a23: Ad<N>,
    a24: Ad<N>,
) -> Ad<N> {
    let a0 = &a0;
    let a1 = &a1;
    let a2 = &a2;
    let a3 = &a3;
    let a4 = &a4;
    let a5 = &a5;
    let a6 = &a6;
    let a7 = &a7;
    let a8 = &a8;
    let a9 = &a9;
    let a10 = &a10;
    let a11 = &a11;
    let a12 = &a12;
    let a13 = &a13;
    let a14 = &a14;
    let a15 = &a15;
    let a16 = &a16;
    let a17 = &a17;
    let a18 = &a18;
    let a19 = &a19;
    let a20 = &a20;
    let a21 = &a21;
    let a22 = &a22;
    let a23 = &a23;
    let a24 = &a24;

    let __intermediate_result_3 = (a0).recip();
    let __intermediate_result_7 = ((a6) + (-((a1) * (a5) * ((a0).recip())))).recip();
    let __intermediate_result_12 = ((a18)
        + (-((a15) * (a3) * ((a0).recip())))
        + (-((((a6) + (-((a1) * (a5) * ((a0).recip())))).recip())
            * ((a16) + (-((a1) * (a15) * ((a0).recip()))))
            * ((a8) + (-((a3) * (a5) * ((a0).recip()))))))
        + (-((((a12)
            + (-((a10) * (a2) * ((a0).recip())))
            + (-((((a6) + (-((a1) * (a5) * ((a0).recip())))).recip())
                * ((a11) + (-((a1) * (a10) * ((a0).recip()))))
                * ((a7) + (-((a2) * (a5) * ((a0).recip())))))))
        .recip())
            * ((a13)
                + (-((a10) * (a3) * ((a0).recip())))
                + (-((((a6) + (-((a1) * (a5) * ((a0).recip())))).recip())
                    * ((a11) + (-((a1) * (a10) * ((a0).recip()))))
                    * ((a8) + (-((a3) * (a5) * ((a0).recip())))))))
            * ((a17)
                + (-((a15) * (a2) * ((a0).recip())))
                + (-((((a6) + (-((a1) * (a5) * ((a0).recip())))).recip())
                    * ((a16) + (-((a1) * (a15) * ((a0).recip()))))
                    * ((a7) + (-((a2) * (a5) * ((a0).recip()))))))))));
    let __intermediate_result_20 = ((a12)
        + (-((a10) * (a2) * ((a0).recip())))
        + (-((((a6) + (-((a1) * (a5) * ((a0).recip())))).recip())
            * ((a11) + (-((a1) * (a10) * ((a0).recip()))))
            * ((a7) + (-((a2) * (a5) * ((a0).recip())))))))
    .recip();
    let __intermediate_result_30 = ((a21) + (-((a1) * (a20) * ((a0).recip()))));
    let __intermediate_result_32 = ((a9) + (-((a4) * (a5) * ((a0).recip()))));
    let __intermediate_result_35 = ((a14)
        + (-((a10) * (a4) * ((a0).recip())))
        + (-((((a6) + (-((a1) * (a5) * ((a0).recip())))).recip())
            * ((a11) + (-((a1) * (a10) * ((a0).recip()))))
            * ((a9) + (-((a4) * (a5) * ((a0).recip())))))));
    let __intermediate_result_38 = ((a22)
        + (-((a2) * (a20) * ((a0).recip())))
        + (-((((a6) + (-((a1) * (a5) * ((a0).recip())))).recip())
            * ((a21) + (-((a1) * (a20) * ((a0).recip()))))
            * ((a7) + (-((a2) * (a5) * ((a0).recip())))))));

    let __intermediate_result_3 = &__intermediate_result_3;
    let __intermediate_result_7 = &__intermediate_result_7;
    let __intermediate_result_12 = &__intermediate_result_12;
    let __intermediate_result_20 = &__intermediate_result_20;
    let __intermediate_result_30 = &__intermediate_result_30;
    let __intermediate_result_32 = &__intermediate_result_32;
    let __intermediate_result_35 = &__intermediate_result_35;
    let __intermediate_result_38 = &__intermediate_result_38;

    ((a0)
        * ((a6) + (-((a1) * (a5) * (__intermediate_result_3))))
        * ((a12)
            + (-((a10) * (a2) * (__intermediate_result_3)))
            + (-((__intermediate_result_7)
                * ((a11) + (-((a1) * (a10) * (__intermediate_result_3))))
                * ((a7) + (-((a2) * (a5) * (__intermediate_result_3)))))))
        * (__intermediate_result_12)
        * ((a24)
            + (-((a20) * (a4) * (__intermediate_result_3)))
            + (-((__intermediate_result_7)
                * (__intermediate_result_30)
                * (__intermediate_result_32)))
            + (-((__intermediate_result_20)
                * (__intermediate_result_35)
                * (__intermediate_result_38)))
            + (-(((__intermediate_result_12).recip())
                * ((a19)
                    + (-((a15) * (a4) * (__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * ((a16) + (-((a1) * (a15) * (__intermediate_result_3))))
                        * (__intermediate_result_32)))
                    + (-((__intermediate_result_20)
                        * (__intermediate_result_35)
                        * ((a17)
                            + (-((a15) * (a2) * (__intermediate_result_3)))
                            + (-((__intermediate_result_7)
                                * ((a16) + (-((a1) * (a15) * (__intermediate_result_3))))
                                * ((a7) + (-((a2) * (a5) * (__intermediate_result_3))))))))))
                * ((a23)
                    + (-((a20) * (a3) * (__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * (__intermediate_result_30)
                        * ((a8) + (-((a3) * (a5) * (__intermediate_result_3))))))
                    + (-((__intermediate_result_20)
                        * ((a13)
                            + (-((a10) * (a3) * (__intermediate_result_3)))
                            + (-((__intermediate_result_7)
                                * ((a11) + (-((a1) * (a10) * (__intermediate_result_3))))
                                * ((a8) + (-((a3) * (a5) * (__intermediate_result_3)))))))
                        * (__intermediate_result_38))))))))
}

#[inline]
pub fn det_5_5<const N: usize>(
    a0: Ad<N>,
    a1: Ad<N>,
    a2: Ad<N>,
    a3: Ad<N>,
    a4: Ad<N>,
    a5: Ad<N>,
    a6: Ad<N>,
    a7: Ad<N>,
    a8: Ad<N>,
    a9: Ad<N>,
    a10: Ad<N>,
    a11: Ad<N>,
    a12: Ad<N>,
    a13: Ad<N>,
    a14: Ad<N>,
    a15: Ad<N>,
    a16: Ad<N>,
    a17: Ad<N>,
    a18: Ad<N>,
    a19: Ad<N>,
    a20: Ad<N>,
    a21: Ad<N>,
    a22: Ad<N>,
    a23: Ad<N>,
    a24: Ad<N>,
) -> Ad<N> {
    let a0 = &a0;
    let a1 = &a1;
    let a2 = &a2;
    let a3 = &a3;
    let a4 = &a4;
    let a5 = &a5;
    let a6 = &a6;
    let a7 = &a7;
    let a8 = &a8;
    let a9 = &a9;
    let a10 = &a10;
    let a11 = &a11;
    let a12 = &a12;
    let a13 = &a13;
    let a14 = &a14;
    let a15 = &a15;
    let a16 = &a16;
    let a17 = &a17;
    let a18 = &a18;
    let a19 = &a19;
    let a20 = &a20;
    let a21 = &a21;
    let a22 = &a22;
    let a23 = &a23;
    let a24 = &a24;

    (((a0) * (a11) * (a17) * (a24) * (a8))
        + ((a0) * (a11) * (a18) * (a22) * (a9))
        + ((a0) * (a11) * (a19) * (a23) * (a7))
        + ((a0) * (a12) * (a16) * (a23) * (a9))
        + ((a0) * (a12) * (a18) * (a24) * (a6))
        + ((a0) * (a12) * (a19) * (a21) * (a8))
        + ((a0) * (a13) * (a16) * (a24) * (a7))
        + ((a0) * (a13) * (a17) * (a21) * (a9))
        + ((a0) * (a13) * (a19) * (a22) * (a6))
        + ((a0) * (a14) * (a16) * (a22) * (a8))
        + ((a0) * (a14) * (a17) * (a23) * (a6))
        + ((a0) * (a14) * (a18) * (a21) * (a7))
        + ((a1) * (a10) * (a17) * (a23) * (a9))
        + ((a1) * (a10) * (a18) * (a24) * (a7))
        + ((a1) * (a10) * (a19) * (a22) * (a8))
        + ((a1) * (a12) * (a15) * (a24) * (a8))
        + ((a1) * (a12) * (a18) * (a20) * (a9))
        + ((a1) * (a12) * (a19) * (a23) * (a5))
        + ((a1) * (a13) * (a15) * (a22) * (a9))
        + ((a1) * (a13) * (a17) * (a24) * (a5))
        + ((a1) * (a13) * (a19) * (a20) * (a7))
        + ((a1) * (a14) * (a15) * (a23) * (a7))
        + ((a1) * (a14) * (a17) * (a20) * (a8))
        + ((a1) * (a14) * (a18) * (a22) * (a5))
        + ((a10) * (a16) * (a2) * (a24) * (a8))
        + ((a10) * (a16) * (a22) * (a3) * (a9))
        + ((a10) * (a16) * (a23) * (a4) * (a7))
        + ((a10) * (a17) * (a21) * (a4) * (a8))
        + ((a10) * (a17) * (a24) * (a3) * (a6))
        + ((a10) * (a18) * (a2) * (a21) * (a9))
        + ((a10) * (a18) * (a22) * (a4) * (a6))
        + ((a10) * (a19) * (a2) * (a23) * (a6))
        + ((a10) * (a19) * (a21) * (a3) * (a7))
        + ((a11) * (a15) * (a2) * (a23) * (a9))
        + ((a11) * (a15) * (a22) * (a4) * (a8))
        + ((a11) * (a15) * (a24) * (a3) * (a7))
        + ((a11) * (a17) * (a20) * (a3) * (a9))
        + ((a11) * (a17) * (a23) * (a4) * (a5))
        + ((a11) * (a18) * (a2) * (a24) * (a5))
        + ((a11) * (a18) * (a20) * (a4) * (a7))
        + ((a11) * (a19) * (a2) * (a20) * (a8))
        + ((a11) * (a19) * (a22) * (a3) * (a5))
        + ((a12) * (a15) * (a21) * (a3) * (a9))
        + ((a12) * (a15) * (a23) * (a4) * (a6))
        + ((a12) * (a16) * (a20) * (a4) * (a8))
        + ((a12) * (a16) * (a24) * (a3) * (a5))
        + ((a12) * (a18) * (a21) * (a4) * (a5))
        + ((a12) * (a19) * (a20) * (a3) * (a6))
        + ((a13) * (a15) * (a2) * (a24) * (a6))
        + ((a13) * (a15) * (a21) * (a4) * (a7))
        + ((a13) * (a16) * (a2) * (a20) * (a9))
        + ((a13) * (a16) * (a22) * (a4) * (a5))
        + ((a13) * (a17) * (a20) * (a4) * (a6))
        + ((a13) * (a19) * (a2) * (a21) * (a5))
        + ((a14) * (a15) * (a2) * (a21) * (a8))
        + ((a14) * (a15) * (a22) * (a3) * (a6))
        + ((a14) * (a16) * (a2) * (a23) * (a5))
        + ((a14) * (a16) * (a20) * (a3) * (a7))
        + ((a14) * (a17) * (a21) * (a3) * (a5))
        + ((a14) * (a18) * (a2) * (a20) * (a6))
        + (-((a0) * (a11) * (a17) * (a23) * (a9)))
        + (-((a0) * (a11) * (a18) * (a24) * (a7)))
        + (-((a0) * (a11) * (a19) * (a22) * (a8)))
        + (-((a0) * (a12) * (a16) * (a24) * (a8)))
        + (-((a0) * (a12) * (a18) * (a21) * (a9)))
        + (-((a0) * (a12) * (a19) * (a23) * (a6)))
        + (-((a0) * (a13) * (a16) * (a22) * (a9)))
        + (-((a0) * (a13) * (a17) * (a24) * (a6)))
        + (-((a0) * (a13) * (a19) * (a21) * (a7)))
        + (-((a0) * (a14) * (a16) * (a23) * (a7)))
        + (-((a0) * (a14) * (a17) * (a21) * (a8)))
        + (-((a0) * (a14) * (a18) * (a22) * (a6)))
        + (-((a1) * (a10) * (a17) * (a24) * (a8)))
        + (-((a1) * (a10) * (a18) * (a22) * (a9)))
        + (-((a1) * (a10) * (a19) * (a23) * (a7)))
        + (-((a1) * (a12) * (a15) * (a23) * (a9)))
        + (-((a1) * (a12) * (a18) * (a24) * (a5)))
        + (-((a1) * (a12) * (a19) * (a20) * (a8)))
        + (-((a1) * (a13) * (a15) * (a24) * (a7)))
        + (-((a1) * (a13) * (a17) * (a20) * (a9)))
        + (-((a1) * (a13) * (a19) * (a22) * (a5)))
        + (-((a1) * (a14) * (a15) * (a22) * (a8)))
        + (-((a1) * (a14) * (a17) * (a23) * (a5)))
        + (-((a1) * (a14) * (a18) * (a20) * (a7)))
        + (-((a10) * (a16) * (a2) * (a23) * (a9)))
        + (-((a10) * (a16) * (a22) * (a4) * (a8)))
        + (-((a10) * (a16) * (a24) * (a3) * (a7)))
        + (-((a10) * (a17) * (a21) * (a3) * (a9)))
        + (-((a10) * (a17) * (a23) * (a4) * (a6)))
        + (-((a10) * (a18) * (a2) * (a24) * (a6)))
        + (-((a10) * (a18) * (a21) * (a4) * (a7)))
        + (-((a10) * (a19) * (a2) * (a21) * (a8)))
        + (-((a10) * (a19) * (a22) * (a3) * (a6)))
        + (-((a11) * (a15) * (a2) * (a24) * (a8)))
        + (-((a11) * (a15) * (a22) * (a3) * (a9)))
        + (-((a11) * (a15) * (a23) * (a4) * (a7)))
        + (-((a11) * (a17) * (a20) * (a4) * (a8)))
        + (-((a11) * (a17) * (a24) * (a3) * (a5)))
        + (-((a11) * (a18) * (a2) * (a20) * (a9)))
        + (-((a11) * (a18) * (a22) * (a4) * (a5)))
        + (-((a11) * (a19) * (a2) * (a23) * (a5)))
        + (-((a11) * (a19) * (a20) * (a3) * (a7)))
        + (-((a12) * (a15) * (a21) * (a4) * (a8)))
        + (-((a12) * (a15) * (a24) * (a3) * (a6)))
        + (-((a12) * (a16) * (a20) * (a3) * (a9)))
        + (-((a12) * (a16) * (a23) * (a4) * (a5)))
        + (-((a12) * (a18) * (a20) * (a4) * (a6)))
        + (-((a12) * (a19) * (a21) * (a3) * (a5)))
        + (-((a13) * (a15) * (a2) * (a21) * (a9)))
        + (-((a13) * (a15) * (a22) * (a4) * (a6)))
        + (-((a13) * (a16) * (a2) * (a24) * (a5)))
        + (-((a13) * (a16) * (a20) * (a4) * (a7)))
        + (-((a13) * (a17) * (a21) * (a4) * (a5)))
        + (-((a13) * (a19) * (a2) * (a20) * (a6)))
        + (-((a14) * (a15) * (a2) * (a23) * (a6)))
        + (-((a14) * (a15) * (a21) * (a3) * (a7)))
        + (-((a14) * (a16) * (a2) * (a20) * (a8)))
        + (-((a14) * (a16) * (a22) * (a3) * (a5)))
        + (-((a14) * (a17) * (a20) * (a3) * (a6)))
        + (-((a14) * (a18) * (a2) * (a21) * (a5))))
}

#[inline]
pub fn det_6_6_lu<const N: usize>(
    a0: Ad<N>,
    a1: Ad<N>,
    a2: Ad<N>,
    a3: Ad<N>,
    a4: Ad<N>,
    a5: Ad<N>,
    a6: Ad<N>,
    a7: Ad<N>,
    a8: Ad<N>,
    a9: Ad<N>,
    a10: Ad<N>,
    a11: Ad<N>,
    a12: Ad<N>,
    a13: Ad<N>,
    a14: Ad<N>,
    a15: Ad<N>,
    a16: Ad<N>,
    a17: Ad<N>,
    a18: Ad<N>,
    a19: Ad<N>,
    a20: Ad<N>,
    a21: Ad<N>,
    a22: Ad<N>,
    a23: Ad<N>,
    a24: Ad<N>,
    a25: Ad<N>,
    a26: Ad<N>,
    a27: Ad<N>,
    a28: Ad<N>,
    a29: Ad<N>,
    a30: Ad<N>,
    a31: Ad<N>,
    a32: Ad<N>,
    a33: Ad<N>,
    a34: Ad<N>,
    a35: Ad<N>,
) -> Ad<N> {
    let a0 = &a0;
    let a1 = &a1;
    let a2 = &a2;
    let a3 = &a3;
    let a4 = &a4;
    let a5 = &a5;
    let a6 = &a6;
    let a7 = &a7;
    let a8 = &a8;
    let a9 = &a9;
    let a10 = &a10;
    let a11 = &a11;
    let a12 = &a12;
    let a13 = &a13;
    let a14 = &a14;
    let a15 = &a15;
    let a16 = &a16;
    let a17 = &a17;
    let a18 = &a18;
    let a19 = &a19;
    let a20 = &a20;
    let a21 = &a21;
    let a22 = &a22;
    let a23 = &a23;
    let a24 = &a24;
    let a25 = &a25;
    let a26 = &a26;
    let a27 = &a27;
    let a28 = &a28;
    let a29 = &a29;
    let a30 = &a30;
    let a31 = &a31;
    let a32 = &a32;
    let a33 = &a33;
    let a34 = &a34;
    let a35 = &a35;

    let __intermediate_result_3 = (a0).recip();
    let __intermediate_result_7 = ((a7) + (-((a1) * (a6) * ((a0).recip())))).recip();
    let __intermediate_result_15 = ((a19) + (-((a1) * (a18) * ((a0).recip()))));
    let __intermediate_result_17 = ((a9) + (-((a3) * (a6) * ((a0).recip()))));
    let __intermediate_result_20 = ((a14)
        + (-((a12) * (a2) * ((a0).recip())))
        + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
            * ((a13) + (-((a1) * (a12) * ((a0).recip()))))
            * ((a8) + (-((a2) * (a6) * ((a0).recip())))))))
    .recip();
    let __intermediate_result_21 = ((a15)
        + (-((a12) * (a3) * ((a0).recip())))
        + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
            * ((a13) + (-((a1) * (a12) * ((a0).recip()))))
            * ((a9) + (-((a3) * (a6) * ((a0).recip())))))));
    let __intermediate_result_24 = ((a20)
        + (-((a18) * (a2) * ((a0).recip())))
        + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
            * ((a19) + (-((a1) * (a18) * ((a0).recip()))))
            * ((a8) + (-((a2) * (a6) * ((a0).recip())))))));
    let __intermediate_result_30 = ((a10) + (-((a4) * (a6) * ((a0).recip()))));
    let __intermediate_result_32 = ((a25) + (-((a1) * (a24) * ((a0).recip()))));
    let __intermediate_result_35 = ((a16)
        + (-((a12) * (a4) * ((a0).recip())))
        + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
            * ((a10) + (-((a4) * (a6) * ((a0).recip()))))
            * ((a13) + (-((a1) * (a12) * ((a0).recip())))))));
    let __intermediate_result_38 = ((a26)
        + (-((a2) * (a24) * ((a0).recip())))
        + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
            * ((a25) + (-((a1) * (a24) * ((a0).recip()))))
            * ((a8) + (-((a2) * (a6) * ((a0).recip())))))));
    let __intermediate_result_42 = ((a21)
        + (-((a18) * (a3) * ((a0).recip())))
        + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
            * ((a19) + (-((a1) * (a18) * ((a0).recip()))))
            * ((a9) + (-((a3) * (a6) * ((a0).recip()))))))
        + (-((((a14)
            + (-((a12) * (a2) * ((a0).recip())))
            + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
                * ((a13) + (-((a1) * (a12) * ((a0).recip()))))
                * ((a8) + (-((a2) * (a6) * ((a0).recip())))))))
        .recip())
            * ((a15)
                + (-((a12) * (a3) * ((a0).recip())))
                + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
                    * ((a13) + (-((a1) * (a12) * ((a0).recip()))))
                    * ((a9) + (-((a3) * (a6) * ((a0).recip())))))))
            * ((a20)
                + (-((a18) * (a2) * ((a0).recip())))
                + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
                    * ((a19) + (-((a1) * (a18) * ((a0).recip()))))
                    * ((a8) + (-((a2) * (a6) * ((a0).recip()))))))))))
    .recip();
    let __intermediate_result_54 = ((a11) + (-((a5) * (a6) * ((a0).recip()))));
    let __intermediate_result_56 = ((a31) + (-((a1) * (a30) * ((a0).recip()))));
    let __intermediate_result_59 = ((a17)
        + (-((a12) * (a5) * ((a0).recip())))
        + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
            * ((a11) + (-((a5) * (a6) * ((a0).recip()))))
            * ((a13) + (-((a1) * (a12) * ((a0).recip())))))));
    let __intermediate_result_62 = ((a32)
        + (-((a2) * (a30) * ((a0).recip())))
        + (-((((a7) + (-((a1) * (a6) * ((a0).recip())))).recip())
            * ((a31) + (-((a1) * (a30) * ((a0).recip()))))
            * ((a8) + (-((a2) * (a6) * ((a0).recip())))))));

    let __intermediate_result_3 = &__intermediate_result_3;
    let __intermediate_result_7 = &__intermediate_result_7;
    let __intermediate_result_15 = &__intermediate_result_15;
    let __intermediate_result_17 = &__intermediate_result_17;
    let __intermediate_result_20 = &__intermediate_result_20;
    let __intermediate_result_21 = &__intermediate_result_21;
    let __intermediate_result_24 = &__intermediate_result_24;
    let __intermediate_result_30 = &__intermediate_result_30;
    let __intermediate_result_32 = &__intermediate_result_32;
    let __intermediate_result_35 = &__intermediate_result_35;
    let __intermediate_result_38 = &__intermediate_result_38;
    let __intermediate_result_42 = &__intermediate_result_42;
    let __intermediate_result_54 = &__intermediate_result_54;
    let __intermediate_result_56 = &__intermediate_result_56;
    let __intermediate_result_59 = &__intermediate_result_59;
    let __intermediate_result_62 = &__intermediate_result_62;

    ((a0)
        * ((a7) + (-((a1) * (a6) * (__intermediate_result_3))))
        * ((a14)
            + (-((a12) * (a2) * (__intermediate_result_3)))
            + (-((__intermediate_result_7)
                * ((a13) + (-((a1) * (a12) * (__intermediate_result_3))))
                * ((a8) + (-((a2) * (a6) * (__intermediate_result_3)))))))
        * ((a21)
            + (-((a18) * (a3) * (__intermediate_result_3)))
            + (-((__intermediate_result_7)
                * (__intermediate_result_15)
                * (__intermediate_result_17)))
            + (-((__intermediate_result_20)
                * (__intermediate_result_21)
                * (__intermediate_result_24))))
        * ((a28)
            + (-((a24) * (a4) * (__intermediate_result_3)))
            + (-((__intermediate_result_7)
                * (__intermediate_result_30)
                * (__intermediate_result_32)))
            + (-((__intermediate_result_20)
                * (__intermediate_result_35)
                * (__intermediate_result_38)))
            + (-((__intermediate_result_42)
                * ((a22)
                    + (-((a18) * (a4) * (__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * (__intermediate_result_30)
                        * (__intermediate_result_15)))
                    + (-((__intermediate_result_20)
                        * (__intermediate_result_35)
                        * (__intermediate_result_24))))
                * ((a27)
                    + (-((a24) * (a3) * (__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * (__intermediate_result_32)
                        * (__intermediate_result_17)))
                    + (-((__intermediate_result_20)
                        * (__intermediate_result_21)
                        * (__intermediate_result_38)))))))
        * ((a35)
            + (-((a30) * (a5) * (__intermediate_result_3)))
            + (-((__intermediate_result_7)
                * (__intermediate_result_54)
                * (__intermediate_result_56)))
            + (-((__intermediate_result_20)
                * (__intermediate_result_59)
                * (__intermediate_result_62)))
            + (-((__intermediate_result_42)
                * ((a23)
                    + (-((a18) * (a5) * (__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * (__intermediate_result_54)
                        * (__intermediate_result_15)))
                    + (-((__intermediate_result_20)
                        * (__intermediate_result_59)
                        * (__intermediate_result_24))))
                * ((a33)
                    + (-((a3) * (a30) * (__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * (__intermediate_result_56)
                        * (__intermediate_result_17)))
                    + (-((__intermediate_result_20)
                        * (__intermediate_result_21)
                        * (__intermediate_result_62))))))
            + (-((((a28)
                + (-((a24) * (a4) * (__intermediate_result_3)))
                + (-((__intermediate_result_7)
                    * (__intermediate_result_30)
                    * (__intermediate_result_32)))
                + (-((__intermediate_result_20)
                    * (__intermediate_result_35)
                    * (__intermediate_result_38)))
                + (-((__intermediate_result_42)
                    * ((a22)
                        + (-((a18) * (a4) * (__intermediate_result_3)))
                        + (-((__intermediate_result_7)
                            * (__intermediate_result_30)
                            * (__intermediate_result_15)))
                        + (-((__intermediate_result_20)
                            * (__intermediate_result_35)
                            * (__intermediate_result_24))))
                    * ((a27)
                        + (-((a24) * (a3) * (__intermediate_result_3)))
                        + (-((__intermediate_result_7)
                            * (__intermediate_result_32)
                            * (__intermediate_result_17)))
                        + (-((__intermediate_result_20)
                            * (__intermediate_result_21)
                            * (__intermediate_result_38)))))))
                .recip())
                * ((a29)
                    + (-((a24) * (a5) * (__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * (__intermediate_result_54)
                        * (__intermediate_result_32)))
                    + (-((__intermediate_result_20)
                        * (__intermediate_result_59)
                        * (__intermediate_result_38)))
                    + (-((__intermediate_result_42)
                        * ((a23)
                            + (-((a18) * (a5) * (__intermediate_result_3)))
                            + (-((__intermediate_result_7)
                                * (__intermediate_result_54)
                                * (__intermediate_result_15)))
                            + (-((__intermediate_result_20)
                                * (__intermediate_result_59)
                                * (__intermediate_result_24))))
                        * ((a27)
                            + (-((a24) * (a3) * (__intermediate_result_3)))
                            + (-((__intermediate_result_7)
                                * (__intermediate_result_32)
                                * (__intermediate_result_17)))
                            + (-((__intermediate_result_20)
                                * (__intermediate_result_21)
                                * (__intermediate_result_38)))))))
                * ((a34)
                    + (-((a30) * (a4) * (__intermediate_result_3)))
                    + (-((__intermediate_result_7)
                        * (__intermediate_result_30)
                        * (__intermediate_result_56)))
                    + (-((__intermediate_result_20)
                        * (__intermediate_result_35)
                        * (__intermediate_result_62)))
                    + (-((__intermediate_result_42)
                        * ((a22)
                            + (-((a18) * (a4) * (__intermediate_result_3)))
                            + (-((__intermediate_result_7)
                                * (__intermediate_result_30)
                                * (__intermediate_result_15)))
                            + (-((__intermediate_result_20)
                                * (__intermediate_result_35)
                                * (__intermediate_result_24))))
                        * ((a33)
                            + (-((a3) * (a30) * (__intermediate_result_3)))
                            + (-((__intermediate_result_7)
                                * (__intermediate_result_56)
                                * (__intermediate_result_17)))
                            + (-((__intermediate_result_20)
                                * (__intermediate_result_21)
                                * (__intermediate_result_62)))))))))))
}
